#pragma once
namespace Graphic {
	enum TEXTURE_ID {
		TEXTURE_DEFAULT, 
		TEXTURE_NORMAL_DEFAULT,
		TEXTURE_NORMAL_COUCH,
		TEXTURE_NORMAL_DIRT,
		TEXTURE_NORMAL_BRICK,
		TEXTURE_NORMAL_WOOD,
		TEXTURE_NORMAL_ROCK,
		TEXTURE_TEST_00,
		TEXTURE_TEST_01,
		TEXTURE_TEST_02,
		TEXTURE_TEST_03,
		TEXTURE_TEST_04,
		TEXTURE_TEST_05,
		TEXTURE_TEST_06,
		ICN_LIGHT
	};
}