#pragma once
namespace Graphic {
	enum KEnum {
		OBJ_TYPE_SOLID,
		OBJ_TYPE_UI,
		OBJ_TYPE_LIGHT,
		MESH_ID_CONE,
		MESH_ID_CYLINDER,
		MESH_ID_CUBE,
		MESH_ID_HELIX,
		MESH_ID_SPHERE,
		MESH_ID_TORUS,
		MESH_ID_PLANE
	};
}