#pragma once
namespace Graphic {
	enum KEnum {
		OBJ_TYPE_SOLID,
		OBJ_TYPE_UI,
		OBJ_TYPE_LIGHT,
		MESH_ID_CONE,
		MESH_ID_CYLINDER,
		MESH_ID_CUBE,
		MESH_ID_HELIX,
		MESH_ID_SPHERE,
		MESH_ID_TORUS,
		MESH_ID_PLANE,

		RENDER_TYPE_DEFAULT, RENDER_TYPE_OTHER,
		RENDER_TYPE_DEPTH,
		RENDER_TYPE_DEFFERED,
		RENDER_TYPE_DEFFERED_DIFFUSE, RENDER_TYPE_DEFFERED_NORMAL, RENDER_TYPE_DEFFERED_WORLD,
		RENDER_TYPE_DEFFERED_LIGHT_SPOTLIGHT,
		RENDER_TYPE_DEFFERED_LIGHT_POINT,
		RENDER_TYPE_DEFFERED_FINAL,
		RENDER_TYPE_UI

	};
}