#pragma once

namespace Graphic {
	enum RENDER_TYPE { 
		DEFAULT, OTHER,
		DEPTH,
		DEFFERED,
		DEFFERED_DIFFUSE, DEFFERED_NORMAL, DEFFERED_WORLD,
		DEFFERED_LIGHT_SPOTLIGHT,
		DEFFERED_LIGHT_POINT,
		DEFFERED_FINAL,
		RENDER_TYPE_UI
	};
}