#pragma once

namespace Graphic {
	enum RENDER_TYPE { 
		DEFAULT, OTHER,
		DEPTH,
		DEFFERED,
		DEFFERED_DIFFUSE, DEFFERED_NORMAL, DEFFERED_WORLD,
		DEFFERED_LIGHT_DIRECTIONAL,
		DEFFERED_LIGHT_POINT,
		DEFFERED_FINAL
	};
}